[phases.setup]
nixPkgs = ["nodejs_24", "git", "ripgrep", "universal-ctags"]

[phases.install]
cmds = [
  "cd quark-ide && npm install",
  "npm install -g opencode@latest"
]

[phases.build]
cmds = ["cd quark-ide && npm run build"]

[start]
cmd = "cd quark-ide && npm run start"
